/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Model.Car;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author manjarekar.m
 */
public class DescribeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Car car;
    
    public DescribeJPanel(Car car) {
        initComponents();
        this.car = car;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveBtn = new javax.swing.JButton();
        uploadimageBtn = new javax.swing.JButton();
        numberofgearsLabel = new javax.swing.JLabel();
        horsepowerLabel = new javax.swing.JLabel();
        gearboxtypeLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        serialTextField = new javax.swing.JTextField();
        dimensionsTextField = new javax.swing.JTextField();
        maxMileageTextField = new javax.swing.JTextField();
        registrationYearTextField = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        vehiclePriceTextField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        modelName = new javax.swing.JLabel();
        serialnumberLabel = new javax.swing.JLabel();
        dimensionsLabel = new javax.swing.JLabel();
        maximummileageLabel = new javax.swing.JLabel();
        registrationyearLabel = new javax.swing.JLabel();
        vehiclepriceLabel = new javax.swing.JLabel();
        safetyratingLabel = new javax.swing.JLabel();
        factorywarrantyLabel = new javax.swing.JLabel();
        fueltypeLabel = new javax.swing.JLabel();
        seatingcapactiyLabel = new javax.swing.JLabel();
        enginecapacityLabel = new javax.swing.JLabel();
        safetyTextField = new javax.swing.JTextField();
        warrantyTextField = new javax.swing.JTextField();
        fuelTypeTextField = new javax.swing.JTextField();
        seatingCapacityTextField = new javax.swing.JTextField();
        engineCapacityTextField = new javax.swing.JTextField();
        numberOfGearsTextField = new javax.swing.JTextField();
        horsePowerTextField = new javax.swing.JTextField();
        gearboxTypeTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();

        setLayout(null);

        saveBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        saveBtn.setText("Save the Description");
        saveBtn.setBorder(new javax.swing.border.MatteBorder(null));
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn);
        saveBtn.setBounds(370, 710, 310, 40);

        uploadimageBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        uploadimageBtn.setText("Upload Image of the Car");
        uploadimageBtn.setBorder(new javax.swing.border.MatteBorder(null));
        uploadimageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadimageBtnActionPerformed(evt);
            }
        });
        add(uploadimageBtn);
        uploadimageBtn.setBounds(370, 640, 310, 40);

        numberofgearsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numberofgearsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberofgearsLabel.setText("Number of Gears");
        add(numberofgearsLabel);
        numberofgearsLabel.setBounds(10, 515, 200, 17);

        horsepowerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        horsepowerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horsepowerLabel.setText("Horsepower");
        add(horsepowerLabel);
        horsepowerLabel.setBounds(10, 553, 200, 17);

        gearboxtypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gearboxtypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gearboxtypeLabel.setText("Gearbox Type");
        add(gearboxtypeLabel);
        gearboxtypeLabel.setBounds(10, 591, 200, 17);

        modelTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        modelTextField.setBorder(new javax.swing.border.MatteBorder(null));
        modelTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(modelTextField);
        modelTextField.setBounds(220, 94, 810, 25);

        serialTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serialTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serialTextField.setBorder(new javax.swing.border.MatteBorder(null));
        serialTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(serialTextField);
        serialTextField.setBounds(220, 132, 810, 25);

        dimensionsTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dimensionsTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dimensionsTextField.setBorder(new javax.swing.border.MatteBorder(null));
        dimensionsTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(dimensionsTextField);
        dimensionsTextField.setBounds(220, 170, 810, 25);

        maxMileageTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maxMileageTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        maxMileageTextField.setBorder(new javax.swing.border.MatteBorder(null));
        maxMileageTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(maxMileageTextField);
        maxMileageTextField.setBounds(220, 208, 810, 25);

        registrationYearTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registrationYearTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        registrationYearTextField.setBorder(new javax.swing.border.MatteBorder(null));
        registrationYearTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(registrationYearTextField);
        registrationYearTextField.setBounds(220, 246, 810, 25);

        banner.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner.setText("Describe the Car");
        banner.setBorder(new javax.swing.border.MatteBorder(null));
        add(banner);
        banner.setBounds(10, 11, 1032, 34);

        vehiclePriceTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehiclePriceTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vehiclePriceTextField.setBorder(new javax.swing.border.MatteBorder(null));
        vehiclePriceTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(vehiclePriceTextField);
        vehiclePriceTextField.setBounds(220, 284, 810, 25);

        colorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Color");
        add(colorLabel);
        colorLabel.setBounds(10, 59, 200, 17);

        modelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelName.setText("Model Name");
        add(modelName);
        modelName.setBounds(10, 97, 200, 17);

        serialnumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serialnumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serialnumberLabel.setText("Serial Number");
        add(serialnumberLabel);
        serialnumberLabel.setBounds(10, 135, 200, 17);

        dimensionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dimensionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimensionsLabel.setText("Dimensions");
        add(dimensionsLabel);
        dimensionsLabel.setBounds(10, 173, 200, 17);

        maximummileageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maximummileageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximummileageLabel.setText("Maximum Mileage");
        add(maximummileageLabel);
        maximummileageLabel.setBounds(10, 211, 200, 17);

        registrationyearLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrationyearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationyearLabel.setText("Registration Year");
        add(registrationyearLabel);
        registrationyearLabel.setBounds(10, 249, 200, 17);

        vehiclepriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehiclepriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehiclepriceLabel.setText("Vehicle Price");
        add(vehiclepriceLabel);
        vehiclepriceLabel.setBounds(10, 287, 200, 17);

        safetyratingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        safetyratingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        safetyratingLabel.setText("Safety Rating");
        add(safetyratingLabel);
        safetyratingLabel.setBounds(10, 325, 200, 17);

        factorywarrantyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        factorywarrantyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factorywarrantyLabel.setText("Factory Warranty");
        add(factorywarrantyLabel);
        factorywarrantyLabel.setBounds(10, 363, 200, 17);

        fueltypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fueltypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fueltypeLabel.setText("Fuel Type");
        add(fueltypeLabel);
        fueltypeLabel.setBounds(10, 401, 200, 17);

        seatingcapactiyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seatingcapactiyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatingcapactiyLabel.setText("Seating Capacity");
        add(seatingcapactiyLabel);
        seatingcapactiyLabel.setBounds(10, 439, 200, 17);

        enginecapacityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enginecapacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enginecapacityLabel.setText("Engine Capacity");
        enginecapacityLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(enginecapacityLabel);
        enginecapacityLabel.setBounds(14, 477, 200, 17);

        safetyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        safetyTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        safetyTextField.setBorder(new javax.swing.border.MatteBorder(null));
        safetyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(safetyTextField);
        safetyTextField.setBounds(220, 322, 810, 25);

        warrantyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warrantyTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        warrantyTextField.setBorder(new javax.swing.border.MatteBorder(null));
        warrantyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(warrantyTextField);
        warrantyTextField.setBounds(222, 360, 810, 25);

        fuelTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fuelTypeTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fuelTypeTextField.setBorder(new javax.swing.border.MatteBorder(null));
        fuelTypeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(fuelTypeTextField);
        fuelTypeTextField.setBounds(222, 398, 810, 25);

        seatingCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatingCapacityTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        seatingCapacityTextField.setBorder(new javax.swing.border.MatteBorder(null));
        seatingCapacityTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(seatingCapacityTextField);
        seatingCapacityTextField.setBounds(222, 436, 810, 25);

        engineCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engineCapacityTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        engineCapacityTextField.setBorder(new javax.swing.border.MatteBorder(null));
        engineCapacityTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(engineCapacityTextField);
        engineCapacityTextField.setBounds(222, 474, 810, 25);

        numberOfGearsTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberOfGearsTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numberOfGearsTextField.setBorder(new javax.swing.border.MatteBorder(null));
        numberOfGearsTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(numberOfGearsTextField);
        numberOfGearsTextField.setBounds(222, 512, 810, 25);

        horsePowerTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horsePowerTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        horsePowerTextField.setBorder(new javax.swing.border.MatteBorder(null));
        horsePowerTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(horsePowerTextField);
        horsePowerTextField.setBounds(222, 550, 810, 25);

        gearboxTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gearboxTypeTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gearboxTypeTextField.setBorder(new javax.swing.border.MatteBorder(null));
        gearboxTypeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(gearboxTypeTextField);
        gearboxTypeTextField.setBounds(222, 588, 810, 25);

        colorTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colorTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        colorTextField.setBorder(new javax.swing.border.MatteBorder(null));
        colorTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        colorTextField.setSelectionStart(2);
        add(colorTextField);
        colorTextField.setBounds(220, 60, 810, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
       
            car.setColor(colorTextField.getText());
            car.setModelName(modelTextField.getText());
            car.setSerialNumber(serialTextField.getText());
            car.setDimensions(dimensionsTextField.getText());
            car.setMaximumMileage(maxMileageTextField.getText());
            car.setRegistrationYear(registrationYearTextField.getText());
            car.setVehiclePrice(vehiclePriceTextField.getText());
            car.setSafetyRating(safetyTextField.getText());
            car.setFactoryWarranty(warrantyTextField.getText());
            car.setFuelType(fuelTypeTextField.getText());
            car.setSeatingCapacity(seatingCapacityTextField.getText());
            car.setEngineCapacity(engineCapacityTextField.getText());
            car.setNumberOfGears(numberOfGearsTextField.getText());
            car.setHorsePower(horsePowerTextField.getText());
            car.setGearBoxType(gearboxTypeTextField.getText());
        
            //prompt user that product was successfully created
            JOptionPane.showMessageDialog(banner, "Car object created successfully");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void uploadimageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadimageBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        
        
        //only jpg and gif images to be accepted
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        
        //choose the file to be uploaded
        chooser.setDialogTitle("Choose Your File");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println(" File to be uploaded: " + chooser.getSelectedFile().getName());
            File file = chooser.getSelectedFile();
            //get file path of the chosen file
            String fullpath = file.getAbsolutePath();
            //System.out.println(fullpath);
            //pass the filepath to car object
            car.setCarImage(fullpath);
            JOptionPane.showMessageDialog(banner, "The car image has been uploaded successfully");
            //enable the Save button only after image has been uploaded
            saveBtn.setEnabled(true);
        }
        else if(returnVal == JFileChooser.ERROR_OPTION){
            //prompt to upload image again
            System.out.println("Please choose the image to be uploaded again");
            
        }
        
    }//GEN-LAST:event_uploadimageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JTextField dimensionsTextField;
    private javax.swing.JTextField engineCapacityTextField;
    private javax.swing.JLabel enginecapacityLabel;
    private javax.swing.JLabel factorywarrantyLabel;
    private javax.swing.JTextField fuelTypeTextField;
    private javax.swing.JLabel fueltypeLabel;
    private javax.swing.JTextField gearboxTypeTextField;
    private javax.swing.JLabel gearboxtypeLabel;
    private javax.swing.JTextField horsePowerTextField;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JTextField maxMileageTextField;
    private javax.swing.JLabel maximummileageLabel;
    private javax.swing.JLabel modelName;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField numberOfGearsTextField;
    private javax.swing.JLabel numberofgearsLabel;
    private javax.swing.JTextField registrationYearTextField;
    private javax.swing.JLabel registrationyearLabel;
    private javax.swing.JTextField safetyTextField;
    private javax.swing.JLabel safetyratingLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField seatingCapacityTextField;
    private javax.swing.JLabel seatingcapactiyLabel;
    private javax.swing.JTextField serialTextField;
    private javax.swing.JLabel serialnumberLabel;
    private javax.swing.JButton uploadimageBtn;
    private javax.swing.JTextField vehiclePriceTextField;
    private javax.swing.JLabel vehiclepriceLabel;
    private javax.swing.JTextField warrantyTextField;
    // End of variables declaration//GEN-END:variables
}
