/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Model.Car;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.awt.Image;


/**
 *
 * @author manjarekar.m
 */

public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    public DisplayJPanel(Car car) {
        initComponents();
        displayCar(car);
    
    }
    
    private void displayCar(Car car)
    {
        String colorName = car.getColor();
        colorTextField.setText(colorName);
        
        String modelName = car.getModelName();
        modelTextField.setText(modelName);

        String serialNumber = car.getSerialNumber();
        serialTextField.setText(serialNumber);
        
        String dimensions = car.getDimensions();
        dimensionsTextField.setText(serialNumber);
        
        String maximumMileage = car.getMaximumMileage();
        maxMileageTextField.setText(maximumMileage);
        
        String registrationYear = car.getRegistrationYear();
        registrationYearTextField.setText(registrationYear);
        
        String vehiclePrice = car.getVehiclePrice();
        vehiclePriceTextField.setText(vehiclePrice);
        
        String safetyRating = car.getSafetyRating();
        safetyTextField.setText(safetyRating);
        
        String factoryWarranty = car.getFactoryWarranty();
        warrantyTextField.setText(factoryWarranty);
        
        String fuelType = car.getFuelType();
        fuelTypeTextField.setText(fuelType);
        
        String seatingCapacity = car.getSeatingCapacity();
        seatingCapacityTextField.setText(seatingCapacity);
        
        String engineCapacity = car.getEngineCapacity();
        engineCapacityTextField.setText(engineCapacity);
        
        String numberOfGears = car.getNumberOfGears();
        numberOfGearsTextField.setText(numberOfGears);
        
        String horsepower = car.getHorsePower();
        horsePowerTextField.setText(horsepower);
        
        String gearboxType = car.getGearBoxType();
        gearboxTypeTextField.setText(gearboxType);
        
        //get the path of the image 
        String carImagePath = car.getCarImage();
        File imagefile = new File(carImagePath);
        BufferedImage img;
        try {
                img = ImageIO.read(imagefile);
                //resizing the image to fit frame size
                Image sizedImage = img.getScaledInstance(805,450,Image.SCALE_SMOOTH);
                //displaying the image using ImageIcon
                imagedisplayLabel.setIcon(new ImageIcon(sizedImage));
                
            }
        catch(IOException e) {
                e.printStackTrace();
            }
        
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        modelName = new javax.swing.JLabel();
        serialnumberLabel = new javax.swing.JLabel();
        dimensionsLabel = new javax.swing.JLabel();
        maximummileageLabel = new javax.swing.JLabel();
        registrationyearLabel = new javax.swing.JLabel();
        vehiclepriceLabel = new javax.swing.JLabel();
        safetyratingLabel = new javax.swing.JLabel();
        factorywarrantyLabel = new javax.swing.JLabel();
        fueltypeLabel = new javax.swing.JLabel();
        seatingcapactiyLabel = new javax.swing.JLabel();
        enginecapacityLabel = new javax.swing.JLabel();
        numberofgearsLabel = new javax.swing.JLabel();
        horsepowerLabel = new javax.swing.JLabel();
        gearboxtypeLabel = new javax.swing.JLabel();
        colorTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        serialTextField = new javax.swing.JTextField();
        dimensionsTextField = new javax.swing.JTextField();
        maxMileageTextField = new javax.swing.JTextField();
        registrationYearTextField = new javax.swing.JTextField();
        vehiclePriceTextField = new javax.swing.JTextField();
        safetyTextField = new javax.swing.JTextField();
        warrantyTextField = new javax.swing.JTextField();
        fuelTypeTextField = new javax.swing.JTextField();
        seatingCapacityTextField = new javax.swing.JTextField();
        engineCapacityTextField = new javax.swing.JTextField();
        numberOfGearsTextField = new javax.swing.JTextField();
        horsePowerTextField = new javax.swing.JTextField();
        gearboxTypeTextField = new javax.swing.JTextField();
        imagelabel = new javax.swing.JLabel();
        imagedisplayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setLayout(null);

        banner.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner.setText("Display the Car");
        banner.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(banner);
        banner.setBounds(10, 11, 1032, 34);

        colorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Color");
        jPanel1.add(colorLabel);
        colorLabel.setBounds(10, 54, 200, 17);

        modelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelName.setText("Model Name");
        jPanel1.add(modelName);
        modelName.setBounds(10, 92, 200, 17);

        serialnumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serialnumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serialnumberLabel.setText("Serial Number");
        jPanel1.add(serialnumberLabel);
        serialnumberLabel.setBounds(10, 130, 200, 17);

        dimensionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dimensionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimensionsLabel.setText("Dimensions");
        jPanel1.add(dimensionsLabel);
        dimensionsLabel.setBounds(10, 168, 200, 17);

        maximummileageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maximummileageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximummileageLabel.setText("Maximum Mileage");
        jPanel1.add(maximummileageLabel);
        maximummileageLabel.setBounds(10, 206, 200, 17);

        registrationyearLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrationyearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationyearLabel.setText("Registration Year");
        jPanel1.add(registrationyearLabel);
        registrationyearLabel.setBounds(10, 244, 190, 17);

        vehiclepriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehiclepriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehiclepriceLabel.setText("Vehicle Price");
        jPanel1.add(vehiclepriceLabel);
        vehiclepriceLabel.setBounds(10, 282, 200, 17);

        safetyratingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        safetyratingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        safetyratingLabel.setText("Safety Rating");
        jPanel1.add(safetyratingLabel);
        safetyratingLabel.setBounds(10, 320, 190, 17);

        factorywarrantyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        factorywarrantyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factorywarrantyLabel.setText("Factory Warranty");
        jPanel1.add(factorywarrantyLabel);
        factorywarrantyLabel.setBounds(10, 361, 200, 17);

        fueltypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fueltypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fueltypeLabel.setText("Fuel Type");
        jPanel1.add(fueltypeLabel);
        fueltypeLabel.setBounds(10, 392, 190, 17);

        seatingcapactiyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seatingcapactiyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatingcapactiyLabel.setText("Seating Capacity");
        jPanel1.add(seatingcapactiyLabel);
        seatingcapactiyLabel.setBounds(10, 427, 200, 17);

        enginecapacityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enginecapacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enginecapacityLabel.setText("Engine Capacity");
        jPanel1.add(enginecapacityLabel);
        enginecapacityLabel.setBounds(10, 468, 200, 17);

        numberofgearsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numberofgearsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberofgearsLabel.setText("Number of Gears");
        jPanel1.add(numberofgearsLabel);
        numberofgearsLabel.setBounds(10, 503, 200, 17);

        horsepowerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        horsepowerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horsepowerLabel.setText("Horsepower");
        jPanel1.add(horsepowerLabel);
        horsepowerLabel.setBounds(10, 544, 200, 17);

        gearboxtypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gearboxtypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gearboxtypeLabel.setText("Gearbox Type");
        jPanel1.add(gearboxtypeLabel);
        gearboxtypeLabel.setBounds(10, 582, 200, 17);

        colorTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colorTextField.setText("                 ");
        colorTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(colorTextField);
        colorTextField.setBounds(222, 51, 810, 25);

        modelTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(modelTextField);
        modelTextField.setBounds(222, 89, 810, 25);

        serialTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serialTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(serialTextField);
        serialTextField.setBounds(222, 127, 810, 25);

        dimensionsTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dimensionsTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(dimensionsTextField);
        dimensionsTextField.setBounds(222, 165, 810, 25);

        maxMileageTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maxMileageTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(maxMileageTextField);
        maxMileageTextField.setBounds(222, 203, 810, 25);

        registrationYearTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registrationYearTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(registrationYearTextField);
        registrationYearTextField.setBounds(222, 241, 810, 25);

        vehiclePriceTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehiclePriceTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(vehiclePriceTextField);
        vehiclePriceTextField.setBounds(222, 279, 810, 25);

        safetyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        safetyTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(safetyTextField);
        safetyTextField.setBounds(222, 317, 810, 25);

        warrantyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warrantyTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(warrantyTextField);
        warrantyTextField.setBounds(222, 355, 810, 25);

        fuelTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fuelTypeTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(fuelTypeTextField);
        fuelTypeTextField.setBounds(222, 389, 810, 25);

        seatingCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatingCapacityTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(seatingCapacityTextField);
        seatingCapacityTextField.setBounds(222, 427, 810, 25);

        engineCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engineCapacityTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(engineCapacityTextField);
        engineCapacityTextField.setBounds(222, 465, 810, 25);

        numberOfGearsTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberOfGearsTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(numberOfGearsTextField);
        numberOfGearsTextField.setBounds(222, 503, 810, 25);

        horsePowerTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horsePowerTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(horsePowerTextField);
        horsePowerTextField.setBounds(222, 541, 810, 25);

        gearboxTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gearboxTypeTextField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(gearboxTypeTextField);
        gearboxTypeTextField.setBounds(222, 579, 810, 25);

        imagelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imagelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagelabel.setText("Car Image");
        jPanel1.add(imagelabel);
        imagelabel.setBounds(10, 620, 180, 17);

        imagedisplayLabel.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(imagedisplayLabel);
        imagedisplayLabel.setBounds(220, 620, 805, 450);

        add(jPanel1);
        jPanel1.setBounds(10, 11, 1180, 1110);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(282, 669, 186, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JTextField dimensionsTextField;
    private javax.swing.JTextField engineCapacityTextField;
    private javax.swing.JLabel enginecapacityLabel;
    private javax.swing.JLabel factorywarrantyLabel;
    private javax.swing.JTextField fuelTypeTextField;
    private javax.swing.JLabel fueltypeLabel;
    private javax.swing.JTextField gearboxTypeTextField;
    private javax.swing.JLabel gearboxtypeLabel;
    private javax.swing.JTextField horsePowerTextField;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JLabel imagedisplayLabel;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxMileageTextField;
    private javax.swing.JLabel maximummileageLabel;
    private javax.swing.JLabel modelName;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField numberOfGearsTextField;
    private javax.swing.JLabel numberofgearsLabel;
    private javax.swing.JTextField registrationYearTextField;
    private javax.swing.JLabel registrationyearLabel;
    private javax.swing.JTextField safetyTextField;
    private javax.swing.JLabel safetyratingLabel;
    private javax.swing.JTextField seatingCapacityTextField;
    private javax.swing.JLabel seatingcapactiyLabel;
    private javax.swing.JTextField serialTextField;
    private javax.swing.JLabel serialnumberLabel;
    private javax.swing.JTextField vehiclePriceTextField;
    private javax.swing.JLabel vehiclepriceLabel;
    private javax.swing.JTextField warrantyTextField;
    // End of variables declaration//GEN-END:variables
}
