/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleet;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Car;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author manja
 */
public class addcarjpanel extends javax.swing.JPanel {
    private JPanel containerjpanel;
    private CarFleet carList;    
    /**
     * Creates new form addcarjpanel
     */
    

    public addcarjpanel(JPanel containerjpanel, CarFleet carList) {
        initComponents();
        this.containerjpanel = containerjpanel;
        this.carList = carList;       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkvalid = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtmanufacturer = new javax.swing.JTextField();
        txtmanufacturedyear = new javax.swing.JTextField();
        txtminnumberofseats = new javax.swing.JTextField();
        txtserialnumber = new javax.swing.JTextField();
        txtmodelnumber = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        checkavailable = new javax.swing.JCheckBox();
        checkexpired = new javax.swing.JCheckBox();
        checknotavailable = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtmaxnumberofseats = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Car Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnback.setText("<< BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Manufactured Year");

        jLabel4.setText("Minimun Number of Seats");

        jLabel5.setText("Serial Number");

        jLabel6.setText("Model Number");

        jLabel7.setText("City");

        jLabel8.setText("Is the Maintenance Certificate Valid/Expired?");

        checkvalid.setText("Valid");
        checkvalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkvalidActionPerformed(evt);
            }
        });

        jLabel9.setText("Is the Car Available Now?");

        txtmanufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanufacturerActionPerformed(evt);
            }
        });

        checkavailable.setText("Available");

        checkexpired.setText("Expired");

        checknotavailable.setText("Not Available");

        jLabel10.setText("Maximum Number of Seats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmanufacturedyear, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtminnumberofseats, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkexpired)
                                            .addComponent(checknotavailable)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtmaxnumberofseats, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtserialnumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                    .addComponent(txtmodelnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkvalid)
                                    .addComponent(checkavailable))))))
                .addGap(117, 212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmanufacturedyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtminnumberofseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmaxnumberofseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmodelnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkvalid)
                        .addComponent(checkexpired)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(checkavailable)
                    .addComponent(checknotavailable))
                .addGap(18, 18, 18)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        containerjpanel.remove(this);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.previous(containerjpanel);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        
        String serialnumber = txtserialnumber.getText();
        String manufacturer = txtmanufacturer.getText();
        Integer manufacturedyear = 0;
        Integer maxnumberofseats = 0;
        Integer minnumberofseats = 0;
        //Integer manufacturedyear = Integer.parseInt(txtmanufacturedyear.getText());
        try
        {
             Integer.parseInt(txtmanufacturedyear.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid year");
        }
        manufacturedyear = Integer.parseInt(txtmanufacturedyear.getText());
        try
        {
              Integer.parseInt(txtmaxnumberofseats.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid max munber of seats");
        }
        maxnumberofseats = Integer.parseInt(txtmaxnumberofseats.getText());
        try
        {
              Integer.parseInt(txtminnumberofseats.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid minimum number of seats");
        }
        minnumberofseats = Integer.parseInt(txtminnumberofseats.getText());
        
        String modelnumber = txtmodelnumber.getText();
        String city = txtcity.getText();
        Boolean maintenancecert = false;
        Boolean isavailable = false;
        
        if(checkvalid.isSelected())
        {
            maintenancecert = true;
        }
        if(checkexpired.isSelected())
        {
             maintenancecert = false;
        }
        if(checkavailable.isSelected())
        {
            isavailable = true;
        }
        if(checknotavailable.isSelected())
        {
             isavailable = false;
        }
        try
        {
            Car newcar = new Car(manufacturer,manufacturedyear,minnumberofseats,maxnumberofseats,serialnumber,modelnumber,city,maintenancecert,isavailable);
            carList.addCar(newcar);
            JOptionPane.showMessageDialog(null, "New Car added Successfully");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        txtmanufacturer.setText("");
        txtmanufacturedyear.setText("");
        txtminnumberofseats.setText("");
        txtmaxnumberofseats.setText("");
        txtmodelnumber.setText("");
        txtcity.setText("");
        txtserialnumber.setText("");
        checkavailable.setSelected(false);
        checkexpired.setSelected(false);
        checkvalid.setSelected(false);
        checknotavailable.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void checkvalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkvalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkvalidActionPerformed

    private void txtmanufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanufacturerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmanufacturerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JCheckBox checkavailable;
    private javax.swing.JCheckBox checkexpired;
    private javax.swing.JCheckBox checknotavailable;
    private javax.swing.JCheckBox checkvalid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmanufacturedyear;
    private javax.swing.JTextField txtmanufacturer;
    private javax.swing.JTextField txtmaxnumberofseats;
    private javax.swing.JTextField txtminnumberofseats;
    private javax.swing.JTextField txtmodelnumber;
    private javax.swing.JTextField txtserialnumber;
    // End of variables declaration//GEN-END:variables
}
