/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarFleet;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author manja
 */
public class adminjpanel extends javax.swing.JPanel {
    private JPanel containerjpanel;
    private CarFleet carList;
    private Integer numberofcaravailable;
    private Integer numberofcarnotavailable;
    private Car availablecar;
    /**
     * Creates new form adminjpanel
     */
    

    public adminjpanel(JPanel containerjpanel, CarFleet carList) {
        initComponents();
        this.containerjpanel = containerjpanel;
        this.carList = carList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnaddcar = new javax.swing.JButton();
        btnviewcar = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FOR THE ADMIN");

        btnaddcar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaddcar.setText("Add Car Details");
        btnaddcar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcarActionPerformed(evt);
            }
        });

        btnviewcar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnviewcar.setText("View Car Details");
        btnviewcar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnviewcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewcarActionPerformed(evt);
            }
        });

        btnback.setText("<< BACK");
        btnback.setBorder(new javax.swing.border.MatteBorder(null));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnaddcar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnviewcar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddcar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewcar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcarActionPerformed
        // TODO add your handling code here:
        addcarjpanel panel = new addcarjpanel(containerjpanel,carList);
        containerjpanel.add("addcarjpanel", panel);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.next(containerjpanel);
    }//GEN-LAST:event_btnaddcarActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        containerjpanel.remove(this);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.previous(containerjpanel);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnviewcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewcarActionPerformed
        // TODO add your handling code here:
        findnumberofcaravailable();
        viewcarjpanel panel = new viewcarjpanel(containerjpanel,carList,numberofcaravailable,numberofcarnotavailable);
        containerjpanel.add("viewcarjpanel", panel);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.next(containerjpanel);
    }//GEN-LAST:event_btnviewcarActionPerformed

    private void findnumberofcaravailable()
    {
        numberofcaravailable=0;
        numberofcarnotavailable=0;
        for(Car availablecar : carList.getCarFleet())
        {
            if(availablecar.getIsAvailable() == true)
            {
                numberofcaravailable = numberofcaravailable + 1;
            }
            else
            {
                numberofcarnotavailable = numberofcarnotavailable + 1;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcar;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnviewcar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
