/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleet;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.ArrayList;
import Business.Car;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manja
 */
public class listjpanel extends javax.swing.JPanel {
    private JPanel containerjpanel;
    private CarFleet carList;
    private ArrayList<String> manufacturer = new ArrayList<String>();
    private Integer size = 0;
    private String[] manufacturer_serial;
    private ArrayList<Car> modelcar = new ArrayList<>();
    private ArrayList<Car> carbyyear = new ArrayList<>();
    private ArrayList<String> manufacturer1 = new ArrayList<>();
   private ArrayList<Car> bymanufacturer = new ArrayList<>();
   private ArrayList<Car> citycarlistsec = new ArrayList<Car>();
    private ArrayList<Car> manucarlistsec = new ArrayList<Car>();
   
    /**
     * Creates new form listjpanel
     */
    

    public listjpanel(JPanel containerjpanel, CarFleet carList, ArrayList<String> manufacturer_serial) {
       initComponents();
       this.containerjpanel = containerjpanel;
       this.carList = carList;
       
        
        for(Car newcar : carList.getCarFleet())
        {
            manufacturer1.add(newcar.getManufacturer());
        }
        DefaultTableModel dtm2 = (DefaultTableModel)tblmanufacturer.getModel();
        dtm2.setRowCount(0);
        
        for(String newcar: manufacturer1)
        {
            Object row[] = new Object[2];
            row[0] = newcar;
            dtm2.addRow(row);
        }
        
        
        
       
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmanudetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblyear = new javax.swing.JTable();
        txtyear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        btnsubmitmodel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblmodel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblmanufacturer = new javax.swing.JTable();
        txtmanufacturer = new javax.swing.JTextField();
        btnsubmitmanu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtcitysec = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtmanusec = new javax.swing.JTextField();
        btnsubmitsec = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblcitymanu = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MORE FILTERS");

        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Filter by Manufacturer:");

        tblmanudetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Min Seats", "Max Seats", "City", "Year"
            }
        ));
        jScrollPane1.setViewportView(tblmanudetails);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Filter by Manufactured Year:");

        tblyear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Min Seats", "Max Seats", "City", "Manufacturer"
            }
        ));
        jScrollPane2.setViewportView(tblyear);

        jLabel4.setText("Please Enter the Year:");

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Filter by Model Number:");

        jLabel6.setText("Please Enter Model Number:");

        btnsubmitmodel.setText("SUBMIT");
        btnsubmitmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitmodelActionPerformed(evt);
            }
        });

        tblmodel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Manufacturer", "Min Seats", "Max Seats", "City", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblmodel);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("List All Manufacturers:");

        tblmanufacturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblmanufacturer);

        btnsubmitmanu.setText("SUBMIT");
        btnsubmitmanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitmanuActionPerformed(evt);
            }
        });

        jLabel8.setText("Please Enter the Manufacturer:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Filter by City and Manufacturer:");

        jLabel15.setText("Please Enter City:");

        jLabel16.setText("Please Enter Manufacturer:");

        txtmanusec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanusecActionPerformed(evt);
            }
        });

        btnsubmitsec.setText("SUBMIT");
        btnsubmitsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitsecActionPerformed(evt);
            }
        });

        tblcitymanu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Max Seats", "Min Seats", "Year"
            }
        ));
        jScrollPane6.setViewportView(tblcitymanu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(txtmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                    .addComponent(btnsubmitmanu))
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsubmit))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsubmitmodel))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcitysec, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmanusec, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsubmitsec))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel7)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmitmanu)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmitmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(txtcitysec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtmanusec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmitsec))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        containerjpanel.remove(this);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.previous(containerjpanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        Integer year = Integer.parseInt(txtyear.getText());
        for(Car newcar : carList.getCarFleet())
        {
            Integer newyear = newcar.getManufactured_year();
            
            if(newyear.equals(year))
            {
                carbyyear.add(newcar);
            }
        }
        
        DefaultTableModel dtm1 = (DefaultTableModel)tblyear.getModel();
        dtm1.setRowCount(0);
        
        for(Car newcar: carbyyear)
        {
            Object row[] = new Object[6];
            row[0] = newcar.getSerial_number();
            row[1] = newcar.getModel_number();
            row[2] = newcar.getMin_Seats();
            row[3] = newcar.getMax_Seats();
            row[4] = newcar.getCity();
            row[5] = newcar.getManufacturer();
            dtm1.addRow(row);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnsubmitmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitmodelActionPerformed
        // TODO add your handling code here:
        String model = txtmodel.getText();
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getModel_number().equals(model))
            {
                modelcar.add(newcar);
            }
        }
        DefaultTableModel dtm1 = (DefaultTableModel)tblmodel.getModel();
        dtm1.setRowCount(0);
        for(Car newmodel : modelcar)
        {
            Object row[] = new Object[6];
            row[0] = newmodel.getSerial_number();
            row[1] = newmodel.getManufacturer();
            row[2] = newmodel.getMin_Seats();
            row[3] = newmodel.getMax_Seats();
            row[4] = newmodel.getCity();
            row[5] = newmodel.getManufacturer();
            dtm1.addRow(row);
        }
        
    }//GEN-LAST:event_btnsubmitmodelActionPerformed

    private void btnsubmitmanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitmanuActionPerformed
        // TODO add your handling code here:
        
        String manufacturer = txtmanufacturer.getText();
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getManufacturer().equals(manufacturer))
            {
                bymanufacturer.add(newcar);
            }
        }
        DefaultTableModel dtm = (DefaultTableModel)tblmanudetails.getModel();
        dtm.setRowCount(0);
        
        for(Car newcar : bymanufacturer)
        {
            Object row[] = new Object[6];
            row[0] = newcar.getSerial_number();
            row[1] = newcar.getModel_number();
            row[2] = newcar.getMin_Seats();
            row[3] = newcar.getMax_Seats();
            row[4] = newcar.getCity();
            row[5] = newcar.getManufactured_year();
            dtm.addRow(row);
        }
    }//GEN-LAST:event_btnsubmitmanuActionPerformed

    private void txtmanusecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanusecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanusecActionPerformed

    private void btnsubmitsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitsecActionPerformed
        // TODO add your handling code here:
        String city = txtcitysec.getText();
        String manufacturer = txtmanusec.getText();

        for(Car newcar: carList.getCarFleet())
        {
            if(newcar.getCity().equals(city))
            {
                citycarlistsec.add(newcar);
            }
        }
        for(Car newcar: citycarlistsec)
        {
            if(newcar.getManufacturer().equals(manufacturer))
            {
                manucarlistsec.add(newcar);
            }
        }
        DefaultTableModel dtm7 = (DefaultTableModel)tblcitymanu.getModel();
        dtm7.setRowCount(0);
        for(Car newcar: manucarlistsec )
        {

            Object row[] = new Object[5];
            row[0] = newcar.getSerial_number();
            row[1] = newcar.getModel_number();
            row[2] = newcar.getMax_Seats();
            row[3] = newcar.getMin_Seats();
            row[4] = newcar.getManufactured_year();
            dtm7.addRow(row);
        }

    }//GEN-LAST:event_btnsubmitsecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnsubmitmanu;
    private javax.swing.JButton btnsubmitmodel;
    private javax.swing.JButton btnsubmitsec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblcitymanu;
    private javax.swing.JTable tblmanudetails;
    private javax.swing.JTable tblmanufacturer;
    private javax.swing.JTable tblmodel;
    private javax.swing.JTable tblyear;
    private javax.swing.JTextField txtcitysec;
    private javax.swing.JTextField txtmanufacturer;
    private javax.swing.JTextField txtmanusec;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
