/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleet;
import java.awt.CardLayout;
import java.util.Date;

/**
 *
 * @author manja
 */
public class Mainjframe extends javax.swing.JFrame {
    public CarFleet carList;
    
    /**
     * Creates new form Mainjframe
     */
    public Mainjframe() {
        initComponents();
        this.carList = new CarFleet();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        uberjpanel = new javax.swing.JPanel();
        btnuber = new javax.swing.JButton();
        containerjpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnuber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnuber.setText("UBER");
        btnuber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnuber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uberjpanelLayout = new javax.swing.GroupLayout(uberjpanel);
        uberjpanel.setLayout(uberjpanelLayout);
        uberjpanelLayout.setHorizontalGroup(
            uberjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uberjpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnuber, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        uberjpanelLayout.setVerticalGroup(
            uberjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uberjpanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnuber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(uberjpanel);

        containerjpanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(containerjpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuberActionPerformed
        // TODO add your handling code here:
        workareajpanel panel = new workareajpanel(containerjpanel,carList);
        containerjpanel.add("workareajpanel", panel);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.next(containerjpanel);
        
    }//GEN-LAST:event_btnuberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnuber;
    private javax.swing.JPanel containerjpanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel uberjpanel;
    // End of variables declaration//GEN-END:variables
}
