/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleet;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Car;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;

/**
 *
 * @author manja
 */
public class viewcarjpanel extends javax.swing.JPanel {
    private JPanel containerjpanel;
    private CarFleet carList;
    private Integer numberofcaravailable;
    private Integer numberofcarnotavailable;
    private ArrayList<String> manufacturer_serial = new ArrayList<String>();
    private Car caraccordingtoseat;
    private Car foundcar;
    private ArrayList<Car> citycarlist = new ArrayList<Car>();
    
    private ArrayList<String> expiredcertlist = new ArrayList<String>();
    
    
    /**
     * Creates new form viewcarjpanel
     */
   

    public viewcarjpanel(JPanel containerjpanel, CarFleet carList, Integer numberofcaravailable, Integer numberofcarnotavailable) 
    {
        initComponents();
        this.containerjpanel = containerjpanel;
        this.carList = carList;
        populateTable();
        //getting latest date catalog was update on
        txtnumberofcarsavailable.setText(numberofcaravailable+"");
        txtnumberofcarsnotavailable.setText(numberofcarnotavailable+"");
        Date lastupdated = carList.lastupdated();
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");  
        String strDate = dateFormat.format(lastupdated); 
        txtlastupdated.setText(strDate);
        
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getMaintenance_cert() == false)
            {
                expiredcertlist.add(newcar.getSerial_number());
            }
        }
        DefaultTableModel dtm6 = (DefaultTableModel)tblexpiredcert.getModel();
        dtm6.setRowCount(0);
        
        for(String newcar: expiredcertlist)
        {
            
            Object row[] = new Object[2];
            row[0] = newcar;
            dtm6.addRow(row);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblviewcar = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnumberofcarsavailable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnumberofcarsnotavailable = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmaxseat = new javax.swing.JTextField();
        txtminseat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtserial = new javax.swing.JTextField();
        btnsubmitserial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblfoundcar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtlastupdated = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        btnsubmitcity = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblcity = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblexpiredcert = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblseat = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW CAR DETAILS");

        tblviewcar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Min Seats", "Max Seats", "City", "Manufacturer", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblviewcar);

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnback.setText("<< BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnlist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlist.setText("MORE FILTER OPTIONS >>");
        btnlist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of Cars currently available:");

        txtnumberofcarsavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberofcarsavailableActionPerformed(evt);
            }
        });

        jLabel4.setText("Number of Cars currently Not Available:");

        txtnumberofcarsnotavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberofcarsnotavailableActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Filter by Seating Capacity:");

        txtmaxseat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaxseatActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MAX_SEATS");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MIN_SEATS");

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Filter by Serial Number:");

        jLabel10.setText("Please Enter Serial Number:");

        btnsubmitserial.setText("SUBMIT");
        btnsubmitserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitserialActionPerformed(evt);
            }
        });

        tblfoundcar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer", "Model Number", "Max Seats", "Min Seats", "City ", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblfoundcar);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Catalog last updated on:");

        txtlastupdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastupdatedActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Filter by City:");

        jLabel13.setText("Please enter the City:");

        btnsubmitcity.setText("SUBMIT");
        btnsubmitcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitcityActionPerformed(evt);
            }
        });

        tblcity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Manufacturer", "Max Seats", "Min Seats", "Year"
            }
        ));
        jScrollPane3.setViewportView(tblcity);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Cars with Expired Cert:");

        tblexpiredcert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number"
            }
        ));
        jScrollPane4.setViewportView(tblexpiredcert);

        tblseat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Manufacturer", "City", "Year"
            }
        ));
        jScrollPane5.setViewportView(tblseat);

        jLabel8.setText("Please Enter the max and min seats:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnumberofcarsnotavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnsubmitcity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnsubmitserial))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtlastupdated, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtmaxseat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtminseat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnsubmit))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnumberofcarsavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnlist, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnlist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnumberofcarsnotavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtnumberofcarsavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnsubmit)
                            .addComponent(txtminseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaxseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsubmitserial))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtlastupdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsubmitcity))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        containerjpanel.remove(this);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.previous(containerjpanel);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblviewcar.getSelectedRow();
        if(selectedRow >= 0)
        {
            Car cartoupdate = (Car)tblviewcar.getValueAt(selectedRow, 0);
            updatecarjpanel panel = new updatecarjpanel(containerjpanel,carList,cartoupdate);
            containerjpanel.add("updatecarjpanel", panel);
            CardLayout layout = (CardLayout)containerjpanel.getLayout();
            layout.next(containerjpanel);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select the row to be updated");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblviewcar.getSelectedRow();
        if(selectedRow >= 0)
        {
            Car cartodelete = (Car)tblviewcar.getValueAt(selectedRow, 0);
            carList.removeCar(cartodelete);
            JOptionPane.showMessageDialog(null, "Car Details deleted");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select the row to be deleted");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtnumberofcarsnotavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberofcarsnotavailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberofcarsnotavailableActionPerformed

    private void btnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistActionPerformed
        // TODO add your handling code here:
        String serial_number = "";
        String car_manu = "";
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getManufacturer().equals("Ferrari"))
            {
                manufacturer_serial.add(newcar.getSerial_number());
            }
            
        }
       
        
        listjpanel panel = new listjpanel(containerjpanel,carList,manufacturer_serial);
        containerjpanel.add("listjpanel", panel);
        CardLayout layout = (CardLayout)containerjpanel.getLayout();
        layout.next(containerjpanel);
    }//GEN-LAST:event_btnlistActionPerformed

    private void txtnumberofcarsavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberofcarsavailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberofcarsavailableActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        Integer min_seat=0;
        try
        {
                Integer.parseInt(txtminseat.getText());
        }
        catch(NumberFormatException e)
        {
                JOptionPane.showMessageDialog(null, "Please enter valid number input");
        }
        min_seat = Integer.parseInt(txtminseat.getText());
        Integer max_seat=0;
        try
        {
                Integer.parseInt(txtmaxseat.getText());
        }
        catch(NumberFormatException e)
        {
                JOptionPane.showMessageDialog(null, "Please enter valid number input");
        }
        max_seat = Integer.parseInt(txtmaxseat.getText());
        
        
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getIsAvailable() == true)
            {
                if(max_seat.equals(newcar.getMax_Seats()))
                {
                    if(min_seat.equals(newcar.getMin_Seats()))
                    {
                        caraccordingtoseat = newcar;
                        break;
                    } 
                }
            }
        }
        DefaultTableModel dtm6 = (DefaultTableModel)tblseat.getModel();
        dtm6.setRowCount(0);
            
            Object row[] = new Object[5];
            row[0] = caraccordingtoseat.getSerial_number();
            row[1] = caraccordingtoseat.getModel_number();
            row[2] = caraccordingtoseat.getManufacturer();
            row[3] = caraccordingtoseat.getCity();
            row[4] = caraccordingtoseat.getManufactured_year();
            dtm6.addRow(row);
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnsubmitserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitserialActionPerformed
        // TODO add your handling code here:
        String serial = txtserial.getText();
        
        for(Car newcar : carList.getCarFleet())
        {
            if(newcar.getSerial_number().equals(serial))
            {
                foundcar = newcar;
            }
        }
        
        DefaultTableModel dtm = (DefaultTableModel)tblfoundcar.getModel();
        dtm.setRowCount(0);
            
            Object row[] = new Object[6];
            row[0] = foundcar.getManufacturer();
            row[1] = foundcar.getModel_number();
            row[2] = foundcar.getMax_Seats();
            row[3] = foundcar.getMin_Seats();
            row[4] = foundcar.getCity();
            row[5] = foundcar.getManufactured_year();
            dtm.addRow(row);
        
    }//GEN-LAST:event_btnsubmitserialActionPerformed

    private void txtlastupdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastupdatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastupdatedActionPerformed

    private void btnsubmitcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitcityActionPerformed
        // TODO add your handling code here:
        String newcity = txtcity.getText();
        
        for(Car newcar : carList.getCarFleet())
        {
           
            if(newcar.getCity().equals(newcity))
            {
                
                citycarlist.add(newcar);
               
            }
        }
        DefaultTableModel dtm5 = (DefaultTableModel)tblcity.getModel();
        dtm5.setRowCount(0);
        
        for(Car newcar: citycarlist)
        {
            
            
            Object row[] = new Object[6];
            row[0] = newcar.getSerial_number();
            row[1] = newcar.getModel_number();
            row[2] = newcar.getManufacturer();
            row[3] = newcar.getMax_Seats();
            row[4] = newcar.getMin_Seats();
            row[5] = newcar.getManufactured_year();
            dtm5.addRow(row);
        }
    }//GEN-LAST:event_btnsubmitcityActionPerformed

    private void txtmaxseatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaxseatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaxseatActionPerformed
    
    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblviewcar.getModel();
        dtm.setRowCount(0);
 
        
        for(Car car : carList.getCarFleet())
        {
            
            Object row[] = new Object[7];
            row[0] = car.getSerial_number();
            row[1] = car.getModel_number();
            row[2] = car.getMin_Seats();
            row[3] = car.getMax_Seats();
            row[4] = car.getCity();
            row[5] = car.getManufacturer();
            row[6] = car.getManufactured_year();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnsubmitcity;
    private javax.swing.JButton btnsubmitserial;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblcity;
    private javax.swing.JTable tblexpiredcert;
    private javax.swing.JTable tblfoundcar;
    private javax.swing.JTable tblseat;
    private javax.swing.JTable tblviewcar;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtlastupdated;
    private javax.swing.JTextField txtmaxseat;
    private javax.swing.JTextField txtminseat;
    private javax.swing.JTextField txtnumberofcarsavailable;
    private javax.swing.JTextField txtnumberofcarsnotavailable;
    private javax.swing.JTextField txtserial;
    // End of variables declaration//GEN-END:variables
}
