/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Flight;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Travel.customerDirectory;
import java.util.List;

/**
 *
 * @author manja
 */
public class adminMainPanel extends javax.swing.JPanel {
private JPanel containerPanel;
private AirlinerDirectory airlineDirectory;
private customerDirectory customerDirectory;
private List<Flight> flights;
/**
     * Creates new form adminMainPanel
     */
    public adminMainPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory, customerDirectory customerDirectory, List<Flight> flights) {
        initComponents();
        this.containerPanel = containerPanel;
        this.airlineDirectory = airlineDirectory;
        this.customerDirectory = customerDirectory;
        this.flights = flights;
        btnmanageAirliner.setFocusPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanageAirliner = new javax.swing.JButton();
        btnmanageFlights = new javax.swing.JButton();
        btnManageCust = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();

        btnmanageAirliner.setText("Manage Airliner");
        btnmanageAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageAirlinerActionPerformed(evt);
            }
        });

        btnmanageFlights.setText("Manage Flights");
        btnmanageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageFlightsActionPerformed(evt);
            }
        });

        btnManageCust.setText("Manage Customers");
        btnManageCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustActionPerformed(evt);
            }
        });

        btnBooking.setText("Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmanageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageCust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmanageAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnmanageAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnmanageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageCust, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanageAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageAirlinerActionPerformed
        manageAirlinerPanel manageairliner = new manageAirlinerPanel(containerPanel,airlineDirectory);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        containerPanel.add("manageAirlinerPanel",manageairliner);
        layout.next(containerPanel);
    }//GEN-LAST:event_btnmanageAirlinerActionPerformed

    private void btnmanageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageFlightsActionPerformed
        // TODO add your handling code here:
        manageFlightsPanel manageflight = new manageFlightsPanel(containerPanel,airlineDirectory);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        containerPanel.add("manageflightPanel",manageflight);
        layout.next(containerPanel);
    }//GEN-LAST:event_btnmanageFlightsActionPerformed

    private void btnManageCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustActionPerformed
        CustomerHomePanel chp = new CustomerHomePanel(this.containerPanel, this.customerDirectory);
        this.containerPanel.add("CustomerHomePanel", chp);
        CardLayout layout = (CardLayout)this.containerPanel.getLayout();
        layout.next(this.containerPanel);
    }//GEN-LAST:event_btnManageCustActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        bookFlightPanel bookFlightPanel1 = new bookFlightPanel(containerPanel, customerDirectory, flights, "Admin");
        containerPanel.add("bookFlightPanel", bookFlightPanel1);
        CardLayout layout = (CardLayout) containerPanel.getLayout();
        layout.next(containerPanel);
    }//GEN-LAST:event_btnBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnManageCust;
    private javax.swing.JButton btnmanageAirliner;
    private javax.swing.JButton btnmanageFlights;
    // End of variables declaration//GEN-END:variables
}
