/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.Airplane;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author phapa
 */
public class AirplaneCreate_update extends javax.swing.JPanel {

    /**
     * Creates new form AirplaneCreate_update
     */
    private JPanel containerPanel;
    private Airliner airliner;
    private Airplane airplane;
    private String typeOfOperation;
    public AirplaneCreate_update(JPanel containerPanel, Airliner airliner,Airplane airplane, String typeOfOperation) {
        initComponents();
        this.airliner = airliner;
        this.containerPanel = containerPanel;
        this.airplane = airplane;
        this.typeOfOperation = typeOfOperation;
        if(this.typeOfOperation.equalsIgnoreCase("UPDATE")){
            this.txtAirlinerModel.setText(airplane.getModel());
            this.txtAirlinerType.setText(airplane.getAirplaneType());
            this.chkIsAvailable.setSelected(this.airplane.getIsAvailable());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirplaneType = new javax.swing.JLabel();
        txtAirlinerType = new javax.swing.JTextField();
        lblAirplaneModel = new javax.swing.JLabel();
        txtAirlinerModel = new javax.swing.JTextField();
        chkIsAvailable = new javax.swing.JCheckBox();
        lblHeader = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblAirplaneType.setText("Type:");

        lblAirplaneModel.setText("Model:");

        chkIsAvailable.setText("IsAvailable");

        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Airplane");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAirplaneType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAirlinerType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAirplaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkIsAvailable)
                                    .addComponent(txtAirlinerModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit)))
                            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirlinerType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirlinerModel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkIsAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap(410, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String type = txtAirlinerType.getText().trim();
        String model = txtAirlinerModel.getText().trim();
        if(!type.equals("") && !model.equals("")){
            if(typeOfOperation.equals("UPDATE")){
                airplane.setModel(model);
                airplane.setAirplaneType(type);
                airplane.setIsAvailable(chkIsAvailable.isSelected());
            }
            else {
                this.airliner.getFleet().addAirplane(type, model,chkIsAvailable.isSelected());
            }
            JOptionPane.showMessageDialog(null, "Operation Successful.");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter valid details.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        containerPanel.remove(this);
        CardLayout layout = (CardLayout) containerPanel.getLayout();
        Component[] comps = this.containerPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof UpdateAirlinerPanel) {
                UpdateAirlinerPanel ch = (UpdateAirlinerPanel) comp;
                ch.populate();
            }
        }
        layout.previous(containerPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkIsAvailable;
    private javax.swing.JLabel lblAirplaneModel;
    private javax.swing.JLabel lblAirplaneType;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAirlinerModel;
    private javax.swing.JTextField txtAirlinerType;
    // End of variables declaration//GEN-END:variables
}
