/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Travel.customerDirectory;
import Business.Users.Customer;
import Business.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author phapa
 */
public class CustomerAdd_Update extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAdd_Update
     */
    private JPanel containerPanel;
    private customerDirectory customerDirectory;
    private Customer customer;
    private String typeOfOperation;

    public CustomerAdd_Update(JPanel containerPanel, customerDirectory customerDirecroty, Customer customer, String typeOfOperation) {
        initComponents();
        this.customerDirectory = customerDirecroty;
        this.containerPanel = containerPanel;
        this.typeOfOperation = typeOfOperation;
        if (this.typeOfOperation.equalsIgnoreCase("UPDATE")) {
            this.customer = customer;
            lblHeader.setText("Update Customer");
            txtUsername.setText(this.customer.getUserName());
            txtPassword.setText(this.customer.getPassword());
            txtName.setText(this.customer.getCustomerName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Add Customer");

        lblName.setText("Name:");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(2, 2, 2)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void HighlightError(JTextField txt, JLabel lbl) {
        txt.setBorder(new LineBorder(Color.RED));
        lbl.setForeground(Color.RED);
    }

    private void resetHighlight() {
        txtUsername.setBorder(new JTextField().getBorder());
        lblUsername.setForeground(Color.BLACK);
        txtPassword.setBorder(new JTextField().getBorder());
        lblPassword.setForeground(Color.BLACK);
        txtName.setBorder(new JTextField().getBorder());
        lblName.setForeground(Color.BLACK);
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        resetHighlight();
        if (txtName == null || txtName.getText().trim().equals("")) {
            HighlightError(txtName, lblName);
            JOptionPane.showMessageDialog(null, "Enter valid name");
            return;
        }
        if (txtUsername == null || !Validation.usernameValidation(txtUsername.getText().trim())) {
            HighlightError(txtUsername, lblUsername);
            JOptionPane.showMessageDialog(null, "Please enter valid username.(xxx_xxx@xxx.xxx)");
            return;
        }
        if (txtPassword == null || !Validation.passwordValidation(txtPassword.getText().trim())) {
            HighlightError(txtPassword, lblPassword);
            JOptionPane.showMessageDialog(null, "Password must contain atleast 6 characters(Uppercase, Lowercase, Special Characters)");
            return;
        }
        if (typeOfOperation.equalsIgnoreCase("CREATE")) {
            if (this.customerDirectory.getCustomerList().stream().anyMatch(x -> x.getUserName().equalsIgnoreCase(txtUsername.getText().trim()))) {
                JOptionPane.showMessageDialog(null, "Username Already present. Try different login.");
                return;
            }
        }
        if (typeOfOperation.equalsIgnoreCase("CREATE")) {
            this.customer = this.customerDirectory.add(txtName.getText(), txtUsername.getText(), txtPassword.getText());
        } else {
            this.customer.setCustomerName(txtName.getText());
            this.customer.setUserName(txtUsername.getText());
            this.customer.setPassword(txtPassword.getText());
        }
        JOptionPane.showMessageDialog(null, "Update Successful");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.containerPanel.remove(this);
        CardLayout layout = (CardLayout) this.containerPanel.getLayout();

        Component[] comps = this.containerPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof CustomerHomePanel) {
                CustomerHomePanel chp = (CustomerHomePanel) comp;
                chp.populate();
            }
        }
        layout.previous(containerPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
