/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Flight;
import Business.Travel.MasterTravelSchedule;
import Business.Travel.TravelAgency;
import Business.config;
import java.awt.CardLayout;
import java.util.List;
import Business.Users.Admin;
import Business.Travel.customerDirectory;
import Business.Users.Customer;
import Business.Validation;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author phapa
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private AirlinerDirectory airlinerDirectory;
    private customerDirectory customerDirectory;

    private TravelAgency travelAgency;
    private MasterTravelSchedule masterTravelSchedule;
    private List<Flight> flights;
    private List<Admin> lstAdmin;

    public MainFrame() {
        initComponents();
        this.airlinerDirectory = config.configureAirlines();
        this.customerDirectory = config.generateUsers();
        this.lstAdmin = config.generateAdmin();

        this.travelAgency = new TravelAgency();
        this.travelAgency.setAirlinerDirectory(this.airlinerDirectory);
        this.travelAgency.setCustomerDirectory(customerDirectory);

        this.masterTravelSchedule = new MasterTravelSchedule();
        this.masterTravelSchedule.setTa(travelAgency);
        this.masterTravelSchedule.loadAllflights();
        this.flights = masterTravelSchedule.getTotalFlights();
        radioAdmin.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        rightmainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radiocustomer = new javax.swing.JRadioButton();
        btnsubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(850);
        splitPane.setResizeWeight(1.0);

        rightmainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Login To Begin");
        rightmainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 290, 174, 106));

        splitPane.setRightComponent(rightmainPanel);

        containerPanel.setLayout(new java.awt.CardLayout());

        lblPassword.setText("Please Enter Your Password:");

        jLabel4.setText("Are You an Admin or Customer?");

        radioAdmin.setText("Admin");
        radioAdmin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioAdminItemStateChanged(evt);
            }
        });
        radioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdminActionPerformed(evt);
            }
        });

        radiocustomer.setText("Customer");
        radiocustomer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiocustomerItemStateChanged(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        lblUsername.setText("Please Enter Your Username:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiocustomer)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtusername)
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioAdmin))
                            .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAdmin))
                .addGap(18, 18, 18)
                .addComponent(radiocustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        containerPanel.add(jPanel1, "card2");

        splitPane.setLeftComponent(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAdminActionPerformed
    private void HighlightError(JTextField txt, JLabel lbl) {
        txt.setBorder(new LineBorder(Color.RED));
        lbl.setForeground(Color.RED);
    }

    private void resetErrorHighlight(JTextField txt, JLabel lbl) {
        txt.setBorder(new JTextField().getBorder());
        lbl.setForeground(Color.BLACK);
    }
    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        resetErrorHighlight(txtusername, lblUsername);
        resetErrorHighlight(txtpassword, lblPassword);

        String username = txtusername.getText().trim();
        String password = txtpassword.getText().trim();
        if (Validation.isEmptyOrNull(username) || Validation.isEmptyOrNull(password)) {
            JOptionPane.showMessageDialog(null, "Username or password can not be empty");
            HighlightError(txtusername, lblUsername);
            HighlightError(txtpassword, lblPassword);
            return;
        }
        //TODO AKSHAY
        if (radiocustomer.isSelected()) {
            boolean flag= false;
            for (Customer cus : this.customerDirectory.getCustomerList()) {
                if ((cus.getUserName().equalsIgnoreCase(username)) && (cus.verify(password))) {
                    cus.setIsActive(true);
                    customerPanel cs = new customerPanel(containerPanel, flights);
                    containerPanel.add("customerpanel", cs);
                    CardLayout layout = (CardLayout) containerPanel.getLayout();
                    layout.next(containerPanel);
                    customerMainPanel customerMainPanel1 = new customerMainPanel(containerPanel, airlinerDirectory, customerDirectory, flights, cus);
                    splitPane.setRightComponent(customerMainPanel1);
                    flag= true;
                } 
            }
            if(!flag){
                HighlightError(txtusername, lblUsername);
                HighlightError(txtpassword, lblPassword);
                JOptionPane.showMessageDialog(null, "Please enter the correct username & passoword");
            }
        }

        if (radioAdmin.isSelected()) {
            if (this.lstAdmin.stream().anyMatch(x -> x.getUserName().equalsIgnoreCase(username) && x.verify(password))) {
                manageAirlinerPanel ap = new manageAirlinerPanel(containerPanel, airlinerDirectory);
                containerPanel.add("manageAirlinerPanel", ap);
                CardLayout layout = (CardLayout) containerPanel.getLayout();
                layout.next(containerPanel);
                adminMainPanel adminMainPanel = new adminMainPanel(containerPanel, airlinerDirectory, customerDirectory,flights);
                splitPane.setRightComponent(adminMainPanel);
            } else {
                HighlightError(txtusername, lblUsername);
                HighlightError(txtpassword, lblPassword);
                JOptionPane.showMessageDialog(null, "Please enter the correct username & passoword");
            }
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void radioAdminItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioAdminItemStateChanged
        if (radioAdmin.isSelected()) {
            radiocustomer.setSelected(false);
        } else {
            radiocustomer.setSelected(true);
        }
    }//GEN-LAST:event_radioAdminItemStateChanged

    private void radiocustomerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiocustomerItemStateChanged
        if (radiocustomer.isSelected()) {
            radioAdmin.setSelected(false);
        } else {
            radioAdmin.setSelected(true);
        }
    }//GEN-LAST:event_radiocustomerItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radiocustomer;
    private javax.swing.JPanel rightmainPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
