/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.AirlinerDirectory;
import javax.swing.JPanel;
import Business.Airliner.Flight;
import Business.Airliner.Airliner;
import Business.Airliner.FlightSchedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manja
 */
public class manageFlightsPanel extends javax.swing.JPanel {

    JPanel containerPanel;
    AirlinerDirectory airlineDirectory;
    Airliner airliner;
    FlightSchedule fs;
    Flight f;
    Object air1;

    /**
     * Creates new form manageFlightPanel
     */
    public manageFlightsPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory) {
        initComponents();

        this.containerPanel = containerPanel;
        this.airlineDirectory = airlineDirectory;
        for (Airliner air : airlineDirectory.getLstAirliner()) {
            comboUser.addItem(air.getAirlinerName());
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboUser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblflight = new javax.swing.JTable();
        btnaddflight = new javax.swing.JButton();
        btndeleteflight = new javax.swing.JButton();
        btnupdateflight = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Flights");

        jLabel2.setText("Please select the Airliner:");

        comboUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUserItemStateChanged(evt);
            }
        });

        tblflight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Start Time", "End Time", "Start Location", "End Location", "Duration"
            }
        ));
        jScrollPane1.setViewportView(tblflight);

        btnaddflight.setText("Add New Flight");
        btnaddflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddflightActionPerformed(evt);
            }
        });

        btndeleteflight.setText("Delete Flight");
        btndeleteflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteflightActionPerformed(evt);
            }
        });

        btnupdateflight.setText("Update Flight");
        btnupdateflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateflightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnaddflight, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdateflight, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndeleteflight, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddflight)
                    .addComponent(btndeleteflight)
                    .addComponent(btnupdateflight))
                .addContainerGap(382, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteflightActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblflight.getSelectedRow();
        if (selectedRow >= 0) {

            Flight f = (Flight) tblflight.getValueAt(selectedRow, 0);
            fs.deleteFlight(f);
            f.getAirplane().setIsAvailable(true);

            //Flight f = (Flight)tblflight.getValueAt(selectedRow, 0);
            JOptionPane.showMessageDialog(null, "Flight deleted successfully");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select the flight to be deleted");
        }
    }//GEN-LAST:event_btndeleteflightActionPerformed

    private void btnaddflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddflightActionPerformed
        // TODO add your handling code here:
        newFlightPanel newf = new newFlightPanel(containerPanel, airlineDirectory, null, "CREATE");
        containerPanel.add("newFlightPanel", newf);
        CardLayout layout = (CardLayout) containerPanel.getLayout();
        layout.next(containerPanel);
    }//GEN-LAST:event_btnaddflightActionPerformed

    private void comboUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUserItemStateChanged
        Airliner a = this.airlineDirectory.getLstAirliner().stream().filter(x -> x.getAirlinerName().equals(comboUser.getSelectedItem().toString())).findFirst().orElse(new Airliner());
        this.fs = a.getFlightSchedule();
        populateTable();
    }//GEN-LAST:event_comboUserItemStateChanged

    private void btnupdateflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateflightActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tblflight.getSelectedRow();

        if (selectedRow >= 0) {
            Flight flight = (Flight) this.tblflight.getValueAt(selectedRow, 0);
            flight.getAirplane().setIsAvailable(true);
            newFlightPanel newf2 = new newFlightPanel(containerPanel, airlineDirectory, flight, "UPDATE");
            containerPanel.add("newFlightPanel", newf2);
            CardLayout layout = (CardLayout) containerPanel.getLayout();
            layout.next(containerPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select the flight to be updated.");
        }

    }//GEN-LAST:event_btnupdateflightActionPerformed

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblflight.getModel();
        dtm.setRowCount(0);

        for (Airliner air : airlineDirectory.getLstAirliner()) {
            if (air.getAirlinerName().equalsIgnoreCase(comboUser.getSelectedItem().toString())) {
                for (Flight f : air.getFlightSchedule().getLstFlights()) {
                    Object[] row = new Object[6];
                    row[0] = f;
                    row[1] = f.getStartTime();
                    row[2] = f.getEndTime();
                    row[3] = f.getStartLocation();
                    row[4] = f.getEndLocation();
                    row[5] = f.getDuration();
                    dtm.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddflight;
    private javax.swing.JButton btndeleteflight;
    private javax.swing.JButton btnupdateflight;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblflight;
    // End of variables declaration//GEN-END:variables
}
