/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Fleet;
import Business.Travel.customerDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manja
 */
public class newAirlinerPanel extends javax.swing.JPanel {

    JPanel containerPanel;
    AirlinerDirectory airlineDirectory;
    Fleet fleet;
    DefaultTableModel dtm;
    int rowcount;

    /**
     * Creates new form newAirlinerPanel
     */
    public newAirlinerPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory) {
        initComponents();
        this.containerPanel = containerPanel;
        this.airlineDirectory = airlineDirectory;
        dtm = (DefaultTableModel) tblAddAirplane.getModel();
        hideFields();
    }

    public void hideFields() {
        lblAddInstruction.setVisible(false);
        tblAddAirplane.setVisible(false);
        btnAddAirplane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnumberplane = new javax.swing.JTextField();
        btnNumberOfEnries = new javax.swing.JButton();
        lblAddInstruction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddAirplane = new javax.swing.JTable();
        btnAddAirplane = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Airliner");

        jLabel2.setText("Please Enter the New Airliner Name:");

        jLabel3.setText("Please Enter the Number of Planes to be Added:");

        btnNumberOfEnries.setText("Next");
        btnNumberOfEnries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberOfEnriesActionPerformed(evt);
            }
        });

        lblAddInstruction.setText("Please Enter the Airplane Details below:");

        tblAddAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Type", "Airplane Model"
            }
        ));
        jScrollPane1.setViewportView(tblAddAirplane);

        btnAddAirplane.setText("SUBMIT");
        btnAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirplaneActionPerformed(evt);
            }
        });

        btnback1.setText("<< BACK");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnback1)
                            .addGap(153, 153, 153)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAddInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnumberplane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(txtAirlinerName, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(btnNumberOfEnries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback1)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnumberplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNumberOfEnries)
                .addGap(10, 10, 10)
                .addComponent(lblAddInstruction)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddAirplane)
                .addContainerGap(400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void HighlightError(JTextField txt, JLabel lbl) {
        txt.setBorder(new LineBorder(Color.RED));
        lbl.setForeground(Color.RED);
    }

    private void resetErrorHighlight(JTextField txt, JLabel lbl) {
        txt.setBorder(new JTextField().getBorder());
        lbl.setForeground(Color.BLACK);
    }
    private void btnNumberOfEnriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberOfEnriesActionPerformed
        // TODO add your handling code here:
        resetErrorHighlight(txtAirlinerName, jLabel2);
        resetErrorHighlight(txtnumberplane, jLabel3);
        if (txtAirlinerName.getText().trim()!="" && txtnumberplane.getText().matches("^[1-9][0-9]*$")) {
            this.rowcount = Integer.parseInt(txtnumberplane.getText());
            this.dtm.setRowCount(rowcount);
            this.lblAddInstruction.setVisible(true);
            this.tblAddAirplane.setVisible(true);
            this.btnAddAirplane.setVisible(true);
            this.txtAirlinerName.setEnabled(false);
            this.txtnumberplane.setEnabled(false);
            this.btnNumberOfEnries.setEnabled(false);
        } else {
            HighlightError(txtAirlinerName, jLabel2);
            HighlightError(txtnumberplane, jLabel3);
            JOptionPane.showMessageDialog(null, "Please enter valid fields.");
        }

    }//GEN-LAST:event_btnNumberOfEnriesActionPerformed

    private void btnAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirplaneActionPerformed
        tblAddAirplane.clearSelection();
        for (int i = 0; i < this.rowcount; i++) {
            for (int j = 0; j < 2; j++) {
                if (tblAddAirplane.getValueAt(i, j) == null) {
                    JOptionPane.showMessageDialog(null, "Please enter all values in the table");
                    return;
                }
            }
        }

        Fleet newfleet = new Fleet();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String airplanetype = dtm.getValueAt(i, 0).toString();
            String airplanemodel = dtm.getValueAt(i, 1).toString();
            newfleet.addAirplane(airplanetype, airplanemodel,true);
        }

        Airliner newairliner = airlineDirectory.addAirliner();
        newairliner.setAirlinerName(txtAirlinerName.getText());
        newairliner.setFleet(newfleet);
        txtAirlinerName.setText("");
        txtnumberplane.setText("");
        this.dtm.setRowCount(0);
        hideFields();
        this.txtAirlinerName.setEnabled(true);
        this.txtnumberplane.setEnabled(true);
        this.btnNumberOfEnries.setEnabled(true);

    }//GEN-LAST:event_btnAddAirplaneActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        containerPanel.remove(this);
        CardLayout layout = (CardLayout) containerPanel.getLayout();
        Component[] comps = this.containerPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof manageAirlinerPanel) {
                manageAirlinerPanel ch = (manageAirlinerPanel) comp;
                ch.populateTable();
            }
        }
        layout.previous(containerPanel);


    }//GEN-LAST:event_btnback1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirplane;
    private javax.swing.JButton btnNumberOfEnries;
    private javax.swing.JButton btnback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddInstruction;
    private javax.swing.JTable tblAddAirplane;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtnumberplane;
    // End of variables declaration//GEN-END:variables
}
