/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.Airplane;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phapa
 */
public class UpdateAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateAirlinerPanel
     */
    private JPanel containerPanel;
    Airliner airliner;

    public UpdateAirlinerPanel(JPanel containerPanel, Airliner airliner) {
        initComponents();
        this.containerPanel = containerPanel;
        this.airliner = airliner;
        txtAirlinerName.setText(this.airliner.getAirlinerName());
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tblAirPlane.getModel();
        dtm.setRowCount(0);

        for (Airplane a : this.airliner.getFleet().getLstAirplane()) {
            Object[] row = new Object[3];
            row[0] = a;
            row[1] = a.getModel();
            row[2] = a.getIsAvailable();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirPlane = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        btnUpdateAirlinerName = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDeleteAirplane = new javax.swing.JButton();
        btnUpdateAirplane = new javax.swing.JButton();
        btnAddAirplane = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update");

        tblAirPlane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Model", "Available"
            }
        ));
        jScrollPane1.setViewportView(tblAirPlane);
        if (tblAirPlane.getColumnModel().getColumnCount() > 0) {
            tblAirPlane.getColumnModel().getColumn(0).setResizable(false);
            tblAirPlane.getColumnModel().getColumn(1).setResizable(false);
            tblAirPlane.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Airliner Name:");

        btnUpdateAirlinerName.setText("Update");
        btnUpdateAirlinerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirlinerNameActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteAirplane.setText("Delete Airplane");
        btnDeleteAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirplaneActionPerformed(evt);
            }
        });

        btnUpdateAirplane.setText("Update Airplane");
        btnUpdateAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirplaneActionPerformed(evt);
            }
        });

        btnAddAirplane.setText("Add Airplane");
        btnAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirplaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAirlinerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateAirlinerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirlinerNameActionPerformed
        if (txtAirlinerName.getText().trim()!="") {
            this.airliner.setAirlinerName(txtAirlinerName.getText());
            JOptionPane.showMessageDialog(null, "Update Successful.");
        } else {
            JOptionPane.showMessageDialog(null, "Please enter valid airliner name.");
            return;
        }

    }//GEN-LAST:event_btnUpdateAirlinerNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.containerPanel.remove(this);
        CardLayout layout = (CardLayout) this.containerPanel.getLayout();

        Component[] comps = this.containerPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof manageAirlinerPanel) {
                manageAirlinerPanel ma = (manageAirlinerPanel) comp;
                ma.populateTable();
            }
        }
        layout.previous(containerPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirplaneActionPerformed
        int selectedRow = this.tblAirPlane.getSelectedRow();
        if (selectedRow >= 0) {
            this.airliner.getFleet().getLstAirplane().remove((Airplane) this.tblAirPlane.getValueAt(selectedRow, 0));
            JOptionPane.showMessageDialog(null, "Airplane Deleted.");
        } else {
            JOptionPane.showMessageDialog(null, "Please select airplane to be deleted");
            return;
        }
        populate();
    }//GEN-LAST:event_btnDeleteAirplaneActionPerformed

    private void btnAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirplaneActionPerformed
        AirplaneCreate_update ac = new AirplaneCreate_update(this.containerPanel, this.airliner, null, "CREATE");
        this.containerPanel.add("AirplaneCreate_update", ac);
        CardLayout layout = (CardLayout) this.containerPanel.getLayout();
        layout.next(this.containerPanel);
    }//GEN-LAST:event_btnAddAirplaneActionPerformed

    private void btnUpdateAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirplaneActionPerformed
        int selectedRow = this.tblAirPlane.getSelectedRow();
        if (selectedRow >= 0) {
            AirplaneCreate_update au = new AirplaneCreate_update(this.containerPanel, this.airliner,(Airplane)this.tblAirPlane.getValueAt(selectedRow, 0) , "UPDATE");
            this.containerPanel.add("AirplaneCreate_update", au);
            CardLayout layout = (CardLayout) this.containerPanel.getLayout();
            layout.next(this.containerPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select airplane to be updated");
        }
    }//GEN-LAST:event_btnUpdateAirplaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirplane;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAirplane;
    private javax.swing.JButton btnUpdateAirlinerName;
    private javax.swing.JButton btnUpdateAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirPlane;
    private javax.swing.JTextField txtAirlinerName;
    // End of variables declaration//GEN-END:variables
}
