/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.AirlinerDirectory;
import Business.Travel.customerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author manja
 */
public class adminPanel extends javax.swing.JPanel {
private JPanel containerPanel;
private AirlinerDirectory airlineDirectory;
private customerDirectory cusDir;
    /**
     * Creates new form adminPanel
     */
    public adminPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory, customerDirectory cusDir) {
        initComponents();
        this.containerPanel = containerPanel;
        this.airlineDirectory = airlineDirectory;
        this.cusDir = cusDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncreateuser = new javax.swing.JButton();
        btnmanagerairliner = new javax.swing.JButton();
        btnmanageflight = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        btncreateuser.setText("Create User >>");
        btncreateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateuserActionPerformed(evt);
            }
        });

        btnmanagerairliner.setText("Manage Airliner");
        btnmanagerairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagerairlinerActionPerformed(evt);
            }
        });

        btnmanageflight.setText("Manage Flights");
        btnmanageflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageflightActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnmanageflight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmanagerairliner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreateuser, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(btnmanagerairliner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnmanageflight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreateuserActionPerformed

    private void btnmanagerairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagerairlinerActionPerformed
        // TODO add your handling code here:
        manageAirlinerPanel manageairliner = new manageAirlinerPanel(containerPanel,airlineDirectory,cusDir);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        containerPanel.add("manageAirlinerPanel",manageairliner);
        layout.next(containerPanel);
    }//GEN-LAST:event_btnmanagerairlinerActionPerformed

    private void btnmanageflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageflightActionPerformed
        // TODO add your handling code here:
        manageFlightsPanel manageflight = new manageFlightsPanel(containerPanel,airlineDirectory,cusDir);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        containerPanel.add("manageflightPanel",manageflight);
        layout.next(containerPanel);
    }//GEN-LAST:event_btnmanageflightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreateuser;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmanageflight;
    private javax.swing.JButton btnmanagerairliner;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
