/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Airplane;
import Business.Airliner.Fleet;
import Business.Airliner.FlightSchedule;
import Business.config;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import Business.Users.Admin;
import Business.Users.Customer;
import Business.Travel.customerDirectory;

/**
 *
 * @author phapa
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private AirlinerDirectory airlineDirectory;
    private customerDirectory cusDir;
    public Admin admin;

    public MainFrame() {
        initComponents();
        this.airlineDirectory = config.configure();
      
//        this.airlineDirector.getLstairliner();
//        Airliner test =this.airlineDirector.getLstairliner().stream().filter(x->x.getAirlinerName().equalsIgnoreCase("Etihad")).findFirst().orElse(new Airliner());
//        List<Fleet> ap= test.getFleet();
//        List<FlightSchedule> fs =test.getFlightSchedule();
//        
//        //get all the flights
//        List<FlightSchedule> sum = new ArrayList();
//        //similarly get all airplanes available
//        List<Fleet> sumap = new ArrayList();
//        for(Airliner al : this.airlineDirector.getLstairliner()){
//            sum.addAll(al.getFlightSchedule());
//            sumap.addAll(al.getFleet());
//        }

        String n = "";
        Airliner etihad= this.airlineDirectory.getLstAirliner().stream().filter(x->x.getAirlinerName().equalsIgnoreCase("Etihad")).findFirst().orElse(new Airliner());
        etihad.getFleet().getLstAirplane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        rightmainPanel = new javax.swing.JPanel();
        btntravelagency = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(850);

        btntravelagency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btntravelagency.setText("Travel Agency");
        btntravelagency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntravelagencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightmainPanelLayout = new javax.swing.GroupLayout(rightmainPanel);
        rightmainPanel.setLayout(rightmainPanelLayout);
        rightmainPanelLayout.setHorizontalGroup(
            rightmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightmainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntravelagency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightmainPanelLayout.setVerticalGroup(
            rightmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightmainPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btntravelagency, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(rightmainPanel);

        containerPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setLeftComponent(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntravelagencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntravelagencyActionPerformed
        // TODO add your handling code here:
        loginPanel panel = new loginPanel(containerPanel,airlineDirectory,cusDir);
        containerPanel.add("loginpanel", panel);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        layout.next(containerPanel);
    }//GEN-LAST:event_btntravelagencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntravelagency;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel rightmainPanel;
    // End of variables declaration//GEN-END:variables
}
