/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.AirlinerDirectory;
import Business.Travel.customerDirectory;
import javax.swing.JPanel;
import Business.Airliner.Flight;
import Business.Airliner.Airliner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manja
 */
public class manageFlightsPanel extends javax.swing.JPanel {
JPanel containerPanel;
AirlinerDirectory airlineDirectory;
customerDirectory cusDir;
Airliner airliner;
Flight f;
    /**
     * Creates new form manageFlightsPanel
     */
  

    public manageFlightsPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory, customerDirectory cusDir) {
        initComponents();
       this.containerPanel = containerPanel;
       this.airlineDirectory = airlineDirectory;
       this.cusDir = cusDir;
       combouser.removeAllItems();
       for(Airliner air : airlineDirectory.getLstAirliner())
       {
           combouser.addItem(air.getAirlinerName().toString());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblflightdetails = new javax.swing.JTable();
        combouser = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Flights");

        btnback.setText("<< BACK");

        jLabel2.setText("Please select the Airliner:");

        tblflightdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start Time", "End Time", "Start Location", "End Location", "Duration"
            }
        ));
        jScrollPane1.setViewportView(tblflightdetails);

        combouser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combouserActionPerformed(evt);
            }
        });

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(combouser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnsubmit)))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combouser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(569, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combouserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combouserActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String str = combouser.getSelectedItem().toString();
        
        
        DefaultTableModel dtm = (DefaultTableModel)tblflightdetails.getModel();
        dtm.setRowCount(0);
        
        
        //for(Flight f : selectedair.getFlightSchedule().getLstFlights())
        //{
            //System.out.println(ar.getFleet().getLstAirplane().size());
            //Object[] row = new Object[5];
            //row[0]=f;
            //row[1]=f.getStartTime();
            //row[2]=f.getEndTime();
            //row[3]=f.getStartLocation();
            //row[4]=f.getEndLocation();
            //row[5]=f.getDuration();
            //dtm.addRow(row);
       // }
    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> combouser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblflightdetails;
    // End of variables declaration//GEN-END:variables
}
