/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Abstract.User;
import Business.Airliner.AirlinerDirectory;
import Business.Travel.customerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Airliner.Airliner;
import javax.swing.JOptionPane;
/**
 *
 * @author manja
 */
public class manageAirlinerPanel extends javax.swing.JPanel {
JPanel containerPanel;
AirlinerDirectory airlineDirectory;
customerDirectory cusDir;
    /**
     * Creates new form manageAirlinerPanel
     */
    
     public manageAirlinerPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory, customerDirectory cusDir) {
        initComponents();
        this.containerPanel = containerPanel;
        this.airlineDirectory = airlineDirectory;
        this.cusDir = cusDir;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblairliner = new javax.swing.JTable();
        btnaddairliner = new javax.swing.JButton();
        btndeleteAirliner = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Airliner");

        tblairliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner ", "Number of Airplanes registered"
            }
        ));
        jScrollPane1.setViewportView(tblairliner);
        if (tblairliner.getColumnModel().getColumnCount() > 0) {
            tblairliner.getColumnModel().getColumn(0).setResizable(false);
            tblairliner.getColumnModel().getColumn(1).setResizable(false);
        }

        btnaddairliner.setText("Add New Airliner");
        btnaddairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddairlinerActionPerformed(evt);
            }
        });

        btndeleteAirliner.setText("Delete Airliner");
        btndeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteAirlinerActionPerformed(evt);
            }
        });

        btnback.setText("<< BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnback)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndeleteAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnaddairliner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnaddairliner)
                .addGap(34, 34, 34)
                .addComponent(btndeleteAirliner)
                .addContainerGap(426, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblairliner.getSelectedRow();
        if(selectedRow >= 0)
        {
            Airliner airlinertodel = (Airliner)tblairliner.getValueAt(selectedRow, 0);
            airlineDirectory.deleteAirliner(airlinertodel);
            JOptionPane.showMessageDialog(null, "Airliner deleted successfully");
            populateTable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select the airliner to be deleted");
    }//GEN-LAST:event_btndeleteAirlinerActionPerformed

    private void btnaddairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddairlinerActionPerformed
        // TODO add your handling code here:
        newAirlinerPanel newap = new newAirlinerPanel(containerPanel,airlineDirectory,cusDir);
        containerPanel.add("newAirlinerPanel", newap);
        CardLayout layout = (CardLayout)containerPanel.getLayout();
        layout.next(containerPanel);
    }//GEN-LAST:event_btnaddairlinerActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         containerPanel.remove(this);
         CardLayout layout = (CardLayout)containerPanel.getLayout();
         layout.previous(containerPanel);
    }//GEN-LAST:event_btnbackActionPerformed
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblairliner.getModel();
        dtm.setRowCount(0);
        
        
        for(Airliner ar : airlineDirectory.getLstAirliner())
        {
            //System.out.println(ar.getFleet().getLstAirplane().size());
            Object[] row = new Object[3];
            row[0]=ar;
            row[2]=ar.getAirlinerName();
            row[1]=ar.getFleet().getLstAirplane().size();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddairliner;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndeleteAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblairliner;
    // End of variables declaration//GEN-END:variables
}
