/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Airplane;
import Business.Airliner.Fleet;
import Business.Travel.customerDirectory;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manja
 */
public class newAirlinerPanel extends javax.swing.JPanel {
JPanel containerPanel;
AirlinerDirectory airlineDirectory;
customerDirectory cusDir;
Fleet fleet;
Airliner newairliner;
DefaultTableModel dtm;
int rowcount;
    /**
     * Creates new form newAirlinerPanel
     */
    
    public newAirlinerPanel(JPanel containerPanel, AirlinerDirectory airlineDirectory, customerDirectory cusDir) {
         initComponents();
         this.containerPanel = containerPanel;
         this.airlineDirectory = airlineDirectory;
         this.cusDir = cusDir;
         dtm = (DefaultTableModel)tblairplaneinput.getModel();
         //this.fleet = fleet;
         
         
        // tblairplaneinput.enableInputMethods(true);
         
         //tblairplaneinput.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtairlineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnsubmitairplanedetails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblairplaneinput = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtcount = new javax.swing.JTextField();
        btnsubmitcount = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Airliner");

        jLabel2.setText("Please Enter the new AirLine Name:");

        jLabel4.setText("Airplane Type:");

        jLabel7.setText("Please Enter the Airplane Details:");

        btnsubmitairplanedetails.setText("SUBMIT");
        btnsubmitairplanedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitairplanedetailsActionPerformed(evt);
            }
        });

        tblairplaneinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AirplaneType", "AirplaneModel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblairplaneinput.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblairplaneinputComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblairplaneinput);

        jLabel3.setText("Please Enter number of airplanes to be added:");

        btnsubmitcount.setText("SUBMIT");
        btnsubmitcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitcountActionPerformed(evt);
            }
        });

        btnback.setText("<< BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnsubmitcount)
                                .addComponent(txtairlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsubmitairplanedetails)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtairlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmitcount))
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsubmitairplanedetails)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitairplanedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitairplanedetailsActionPerformed
        // TODO add your handling code here:
       tblairplaneinput.clearSelection();
            Fleet newfleet = new Fleet();
         for(int i=0;i<dtm.getRowCount();i++)
         {
             
            // System.out.println(dtm.getColumnName(i));
             String airplanetype = dtm.getValueAt(i, 0).toString();
             System.out.println(airplanetype);
             String airplanemodel = dtm.getValueAt(i, 1).toString();
             System.out.println(airplanemodel);
             newfleet.addAirplane(airplanetype,airplanemodel);
         }
         
         newairliner = airlineDirectory.addAirliner();
         newairliner.setAirlinerName(txtairlineName.getText());
         newairliner.setFleet(newfleet);
         
         //System.out.println(fleet.getLstAirplane());
         
    }//GEN-LAST:event_btnsubmitairplanedetailsActionPerformed

    private void tblairplaneinputComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblairplaneinputComponentShown
        // TODO add your handling code here:
        tblairplaneinput.enableInputMethods(true);
    }//GEN-LAST:event_tblairplaneinputComponentShown

    private void btnsubmitcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitcountActionPerformed
        // TODO add your handling code here:
        rowcount = Integer.parseInt(txtcount.getText());
        dtm.setRowCount(rowcount);
    }//GEN-LAST:event_btnsubmitcountActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         containerPanel.remove(this);
         CardLayout layout = (CardLayout)containerPanel.getLayout();
         layout.previous(containerPanel);
    }//GEN-LAST:event_btnbackActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmitairplanedetails;
    private javax.swing.JButton btnsubmitcount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblairplaneinput;
    private javax.swing.JTextField txtairlineName;
    private javax.swing.JTextField txtcount;
    // End of variables declaration//GEN-END:variables
}
